/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import utilidades.Utilidades;
import static vistas.MenuPrincipal.nombre_completoo;

/**
 *
 * @author mario
 */
public class NuevaConsulta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevaConsulta.class.getName());

    public static String tipoo = Login.datosPersonal[2];
    
    /**
     * Creates new form NuevaConsulta
     */
    public NuevaConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        if (tipoo.equals("MEDICO")) {
            
            labelTitulo.setText("CONSULTA MÉDICA");
            jlabel7.setText("HITORIAL DE CONSULTAS MÉDICAS");
            tablaMed.setVisible(true);
            jScrollPane1.setVisible(true);
            tablaEnf.setVisible(false);
            jScrollPane2.setVisible(false);
            
            campoDNI.setEnabled(true);
            botonDNI.setEnabled(true);
            panelPaciente.setEnabled(false);
            campoNombre.setEnabled(false);
            campoApellidos.setEnabled(false);
            campoTelefono.setEnabled(false);
            campoEmail.setEnabled(false);
            botonInforme.setEnabled(false);
            botonCita.setEnabled(false);
            tablaMed.setEnabled(false);
            botonActualizar.setEnabled(false);
   
        } else if (tipoo.equals("ENFERMERIA")){
            
            labelTitulo.setText("CONSULTA ENFERMERÍA");
            jlabel7.setText("HITORIAL DE CONSULTAS DE ENFERMERÍA");
            tablaMed.setVisible(false);
            jScrollPane1.setVisible(false);
            tablaEnf.setVisible(true);
            jScrollPane2.setVisible(true);
            
            campoDNI.setEnabled(true);
            botonDNI.setEnabled(true);
            panelPaciente.setEnabled(false);
            campoNombre.setEnabled(false);
            campoApellidos.setEnabled(false);
            campoTelefono.setEnabled(false);
            campoEmail.setEnabled(false);
            botonInforme.setEnabled(false);
            botonCita.setEnabled(false);
            tablaMed.setEnabled(false);
            botonActualizar.setEnabled(false);
            
        } else {
            
            JOptionPane.showMessageDialog(this, "Usuario no encontrado: " + nombre_completoo, "Error. Recuperar Usuario.", JOptionPane.WARNING_MESSAGE);
            
            labelTitulo.setText("");
            campoDNI.setEnabled(false);
            botonDNI.setEnabled(false);
            panelPaciente.setEnabled(false);
            campoNombre.setEnabled(false);
            campoApellidos.setEnabled(false);
            campoTelefono.setEnabled(false);
            campoEmail.setEnabled(false);
            botonInforme.setEnabled(false);
            botonCita.setEnabled(false);
            tablaMed.setEnabled(false);
            botonActualizar.setEnabled(false);
             
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelA = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        panelPaciente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonInforme = new javax.swing.JButton();
        botonCita = new javax.swing.JButton();
        botonDNI = new javax.swing.JButton();
        jlabel7 = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMed = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEnf = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabell1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(940, 532));
        setMinimumSize(new java.awt.Dimension(940, 532));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        labelA.setForeground(new java.awt.Color(255, 255, 255));
        labelA.setText("DNI PACIENTE");

        campoDNI.setName("DNI"); // NOI18N
        campoDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDNIFocusLost(evt);
            }
        });

        panelPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelPaciente.setOpaque(false);

        jLabel1.setText("NOMBRE");

        campoNombre.setName("NOMBRE"); // NOI18N

        jLabel2.setText("APELLIDOS");

        campoApellidos.setName("APELLIDOS"); // NOI18N

        campoTelefono.setName("TELÉFONO"); // NOI18N

        jLabel3.setText("TELÉFONO");

        campoEmail.setName("EMAIL"); // NOI18N

        jLabel4.setText("EMAIL");

        botonInforme.setText("NUEVO INFORME");
        botonInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformeActionPerformed(evt);
            }
        });

        botonCita.setText("NUEVA CITA");
        botonCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPacienteLayout = new javax.swing.GroupLayout(panelPaciente);
        panelPaciente.setLayout(panelPacienteLayout);
        panelPacienteLayout.setHorizontalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonInforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelPacienteLayout.setVerticalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInforme)
                    .addComponent(botonCita))
                .addGap(22, 22, 22))
        );

        botonDNI.setText("BUSCAR PACIENTE");
        botonDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDNIActionPerformed(evt);
            }
        });

        jlabel7.setForeground(new java.awt.Color(255, 255, 255));
        jlabel7.setText("DNI PACIENTE");

        botonActualizar.setText("ACTUALIZAR");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        tablaMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "DIAGNÓSTICO", "TRATAMIENTO", "OBSERVACIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMed);

        tablaEnf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "MÁXIMA", "MÍNIMA", "GLUCOSA", "PESO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEnf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEnfMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEnf);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelA)
                                .addGap(18, 18, 18)
                                .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(botonDNI))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA)
                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDNI))
                .addGap(18, 18, 18)
                .addComponent(panelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel7)
                    .addComponent(botonActualizar))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 204, 204));
        labelTitulo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabell1)
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabell1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(484, 484, 484))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDNIActionPerformed
        ComprobarPaciente();
    }//GEN-LAST:event_botonDNIActionPerformed

    private void botonCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCitaActionPerformed
        if (tipoo.equals("MEDICO")) {

            NuevaCitaMedica ncm = new NuevaCitaMedica(this, true);
            ncm.setVisible(true);

        } else if (tipoo.equals("ENFERMERIA")) {

            NuevaCitaEnfermeria nce = new NuevaCitaEnfermeria(this, true);
            nce.setVisible(true);

        }
    }//GEN-LAST:event_botonCitaActionPerformed

    private void botonInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformeActionPerformed
        if (tipoo.equals("MEDICO")) {

            NuevoInformeMedico nim = new NuevoInformeMedico(this, true);
            nim.setVisible(true);

        } else if (tipoo.equals("ENFERMERIA")) {

            NuevoInformeEnfermeria nie = new NuevoInformeEnfermeria(this, true);
            nie.setVisible(true);

        }
    }//GEN-LAST:event_botonInformeActionPerformed

    private void campoDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDNIFocusLost
        campoDNI.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoDNIFocusLost

    private void campoDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDNIFocusGained
        campoDNI.setBackground(Color.LIGHT_GRAY);
        campoDNI.setText("");
    }//GEN-LAST:event_campoDNIFocusGained

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        if (tipoo.equals("MEDICO")) {

            Conexion.conectar();
            DefaultTableModel modelo = (DefaultTableModel) tablaMed.getModel();
            modelo.setRowCount(0);
            Conexion.cargarTablaConsultasMedicas(modelo, pacienteConsultado.getDni());
            Conexion.cerrarConexion();

        } else if (tipoo.equals("ENFERMERIA")) {

            Conexion.conectar();
            DefaultTableModel modelo = (DefaultTableModel) tablaEnf.getModel();
            modelo.setRowCount(0);
            Conexion.cargarTablaConsultasEnfermeria(modelo, pacienteConsultado.getDni());
            Conexion.cerrarConexion();

        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void tablaMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedMouseClicked
        verFila();
    }//GEN-LAST:event_tablaMedMouseClicked

    private void tablaEnfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEnfMouseClicked
        verFila();
    }//GEN-LAST:event_tablaEnfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NuevaConsulta dialog = new NuevaConsulta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCita;
    private javax.swing.JButton botonDNI;
    private javax.swing.JButton botonInforme;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabell1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelPaciente;
    private javax.swing.JTable tablaEnf;
    private javax.swing.JTable tablaMed;
    // End of variables declaration//GEN-END:variables
    
    /*
    
    if (tipoo.equals("MEDICO)) {
    
    Conexion.conectar();
    DefaultTableModel modelo = (DefaultTableModel) tablaMed.getModel();
    modelo.setRowCount(0);
    Conexion.cargarTablaConsultasMedicas(modelo, pacienteConsultado.getDni());
    Conexion.cerrarConexion();
    
    } else if (tipoo.equals("ENFERMERIA")) {
    
    Conexion.conectar();
    DefaultTableModel modelo = (DefaultTableModel) tablaEnf.getModel();
    modelo.setRowCount(0);
    Conexion.cargarTablaConsultasEnfermeria(modelo, pacienteConsultado.getDni());
    Conexion.cerrarConexion();
    
    }
    
    
    
    
    
    if (tipoo.equals("MEDICO)) {
    
    NuevoInformeMedico nim = new NuevoInformeMedico(this, true);
    nim.setVisible(true);
    
    } else if (tipoo.equals("ENFERMERIA")) {
    
    NuevoInformeEnfermeria nie = new NuevoInformeEnfermeria(this, true);
    nie.setVisible(true);
    
    }
    
    
    
    
    
    
    if (tipoo.equals("MEDICO)) {
    
    NuevaCitaMedica ncm = new NuevaCitaMedica(this, true);
    ncm.setVisible(true);
    
    } else if (tipoo.equals("ENFERMERIA")) {
    
    NuevaCitaEnfermeria nce = new NuevaCitaEnfermeria(this, true);
    nce.setVisible(true);
    
    }
    
    
    
    
    ComprobarPaciente();
    
    verFila();
    
    verFila();
    
    campoDNI.setBackground(Color.LIGHT_GRAY);
    campoDNI.setText("");
    
    campoDNI.setBackground(Color.WHITE);
    
    
    */

    
    
    
    public static modelo.Paciente pacienteConsultado;
    public static String dniPacienteNuevo;
    
    public boolean ComprobarPaciente() {
        
        if (tipoo.equals("MEDICO")) {

        Conexion.conectar();
        
        try {
        
            String dniEscrito = campoDNI.getText();
            NuevaConsulta.dniPacienteNuevo = dniEscrito;
            
            if (!Utilidades.ValidaCampoVacio(campoDNI)) {
                return false;
            } else if (!Utilidades.ValidarDNI(campoDNI.getText())) {
                campoDNI.setBackground(Color.RED);
                campoDNI.setText("00000000X");
                return false;
            }
    
            if (Conexion.compruebaDNI(dniEscrito)) {
                pacienteConsultado = Conexion.recuperaDatosPaciente(dniEscrito);
                
                campoDNI.setEnabled(false);
                campoDNI.setEditable(false);
                botonDNI.setEnabled(false);
                
                panelPaciente.setEnabled(true);
                campoNombre.setEnabled(true);
                campoNombre.setEditable(false);
                campoApellidos.setEnabled(true);
                campoApellidos.setEditable(false);
                campoTelefono.setEnabled(true);
                campoTelefono.setEditable(false);
                campoEmail.setEnabled(true);
                campoEmail.setEditable(false);
                        
                botonInforme.setEnabled(true);
                botonCita.setEnabled(true);
                   
                tablaMed.setEnabled(true);
                botonActualizar.setEnabled(true);
                      
                campoNombre.setText(pacienteConsultado.getNombre());
                campoApellidos.setText(pacienteConsultado.getApellidos());
                campoTelefono.setText(Integer.toString(pacienteConsultado.getTelefono()));
                campoEmail.setText(pacienteConsultado.getEmail());
                
                // Conexion.conectar(); // ESTARIA 2 VECES
                
                DefaultTableModel modelo = (DefaultTableModel) tablaMed.getModel();
                modelo.setRowCount(0);
                Conexion.cargarTablaConsultasMedicas(modelo, pacienteConsultado.getDni());
                // Conexion.cerrarConexion(); // ESTARIA 2 VECES, MEJOR EN FINALLY
                return true;
          
            } else {
                
                int opcion = JOptionPane.showConfirmDialog(null, "Este paciente no está registrado. ¿Quiere registrarlo?", "Error. Recuperar Usuario.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

                if (opcion == JOptionPane.OK_OPTION) {
    
                    System.out.println("Recuperando paciente...");
                    
                    campoDNI.setEnabled(true);
                    campoDNI.setEditable(true);
                    botonDNI.setEnabled(true);

                    panelPaciente.setEnabled(false);
                    campoNombre.setEnabled(false);
                    campoNombre.setEditable(false);
                    campoApellidos.setEnabled(false);
                    campoApellidos.setEditable(false);
                    campoTelefono.setEnabled(false);
                    campoTelefono.setEditable(false);
                    campoEmail.setEnabled(false);
                    campoEmail.setEditable(false);

                    botonInforme.setEnabled(false);
                    botonCita.setEnabled(false);

                    tablaMed.setEnabled(false);
                    botonActualizar.setEnabled(false);
                    
                    NuevoPaciente np = new NuevoPaciente(this, true);
                    np.setVisible(true);
                    
 
                    
                } else {

                    System.out.println("Acción cancelada.");
                    
                    campoDNI.setEnabled(true);
                    campoDNI.setEditable(true);
                    botonDNI.setEnabled(true);

                    panelPaciente.setEnabled(false);
                    campoNombre.setEnabled(false);
                    campoNombre.setEditable(false);
                    campoApellidos.setEnabled(false);
                    campoApellidos.setEditable(false);
                    campoTelefono.setEnabled(false);
                    campoTelefono.setEditable(false);
                    campoEmail.setEnabled(false);
                    campoEmail.setEditable(false);

                    botonInforme.setEnabled(false);
                    botonCita.setEnabled(false);

                    tablaMed.setEnabled(false);
                    botonActualizar.setEnabled(false);
                    
                }
                
                return false;
                
            }
    
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Ha habido un error inesperado: " + ex.getMessage(), "Error. Comprobar Usuario.", JOptionPane.WARNING_MESSAGE);
            return false;
        } finally {
            Conexion.cerrarConexion();
        }
            

    } else if (tipoo.equals("ENFERMERIA")) {

        Conexion.conectar();
        
        try {
        
            String dniEscrito = campoDNI.getText();
            NuevaConsulta.dniPacienteNuevo = dniEscrito;
            
            if (!Utilidades.ValidaCampoVacio(campoDNI)) {
                return false;
            } else if (!Utilidades.ValidarDNI(campoDNI.getText())) {
                campoDNI.setBackground(Color.RED);
                campoDNI.setText("00000000X");
                return false;
            }
    
            if (Conexion.compruebaDNI(dniEscrito)) {
                pacienteConsultado = Conexion.recuperaDatosPaciente(dniEscrito);
                
                campoDNI.setEnabled(false);
                campoDNI.setEditable(false);
                botonDNI.setEnabled(false);
                
                panelPaciente.setEnabled(true);
                campoNombre.setEnabled(true);
                campoNombre.setEditable(false);
                campoApellidos.setEnabled(true);
                campoApellidos.setEditable(false);
                campoTelefono.setEnabled(true);
                campoTelefono.setEditable(false);
                campoEmail.setEnabled(true);
                campoEmail.setEditable(false);
                        
                botonInforme.setEnabled(true);
                botonCita.setEnabled(true);
                   
                tablaEnf.setEnabled(true);
                botonActualizar.setEnabled(true);
                      
                campoNombre.setText(pacienteConsultado.getNombre());
                campoApellidos.setText(pacienteConsultado.getApellidos());
                campoTelefono.setText(Integer.toString(pacienteConsultado.getTelefono()));
                campoEmail.setText(pacienteConsultado.getEmail());
                
                // Conexion.conectar(); // ESTARIA 2 VECES
                
                DefaultTableModel modelo = (DefaultTableModel) tablaEnf.getModel();
                modelo.setRowCount(0);
                Conexion.cargarTablaConsultasEnfermeria(modelo, pacienteConsultado.getDni());
                // Conexion.cerrarConexion(); // ESTARIA 2 VECES, MEJOR EN FINALLY
                return true;
          
            } else {
                
                int opcion = JOptionPane.showConfirmDialog(null, "Este paciente no está registrado. ¿Quiere registrarlo?", "Error. Recuperar Usuario.", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

                if (opcion == JOptionPane.OK_OPTION) {
    
                    System.out.println("Recuperando paciente...");
                    
                    campoDNI.setEnabled(true);
                    campoDNI.setEditable(true);
                    botonDNI.setEnabled(true);

                    panelPaciente.setEnabled(false);
                    campoNombre.setEnabled(false);
                    campoNombre.setEditable(false);
                    campoApellidos.setEnabled(false);
                    campoApellidos.setEditable(false);
                    campoTelefono.setEnabled(false);
                    campoTelefono.setEditable(false);
                    campoEmail.setEnabled(false);
                    campoEmail.setEditable(false);

                    botonInforme.setEnabled(false);
                    botonCita.setEnabled(false);

                    tablaEnf.setEnabled(false);
                    botonActualizar.setEnabled(false);
                    
                    NuevoPaciente np = new NuevoPaciente(this, true);
                    np.setVisible(true);
                    
 
                    
                } else {

                    System.out.println("Acción cancelada.");
                    
                    campoDNI.setEnabled(true);
                    campoDNI.setEditable(true);
                    botonDNI.setEnabled(true);

                    panelPaciente.setEnabled(false);
                    campoNombre.setEnabled(false);
                    campoNombre.setEditable(false);
                    campoApellidos.setEnabled(false);
                    campoApellidos.setEditable(false);
                    campoTelefono.setEnabled(false);
                    campoTelefono.setEditable(false);
                    campoEmail.setEnabled(false);
                    campoEmail.setEditable(false);

                    botonInforme.setEnabled(false);
                    botonCita.setEnabled(false);

                    tablaEnf.setEnabled(false);
                    botonActualizar.setEnabled(false);
                    
                }
                
                return false;
                
            }
    
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Ha habido un error inesperado: " + ex.getMessage(), "Error. Comprobar Usuario.", JOptionPane.WARNING_MESSAGE);
            return false;
        } finally {
            Conexion.cerrarConexion();
        }
        
    } return false;

} 
    
private void verFila() {
    
    if (tipoo.equals("MEDICO")) {

        String contenido = "FECHA DE CONSULTA: " + String.valueOf(tablaMed.getValueAt(tablaMed.getSelectedRow(), 0));
        contenido += "\n\nDIAGNÓSTICO:\n : " + String.valueOf(tablaMed.getValueAt(tablaMed.getSelectedRow(), 1));
        contenido += "\n\nTRATAMIENTO:\n : " + String.valueOf(tablaMed.getValueAt(tablaMed.getSelectedRow(), 2));
        contenido += "\n\nOBSERVACIONES:\n : " + String.valueOf(tablaMed.getValueAt(tablaMed.getSelectedRow(), 3));
    
        JTextArea t = new JTextArea(20, 60);
        t.setText(contenido);
        t.setEditable(false);
        t.setLineWrap(false);
        t.setFocusable(false);
        t.setAutoscrolls(false);
        t.setMargin(new Insets(10, 10, 10, 10));
        
        JOptionPane.showMessageDialog(this,new JScrollPane(t), "INFORME", 1);
        
    } else if (tipoo.equals("ENFERMERIA")) {

        String contenido = "FECHA DE CONSULTA: " + String.valueOf(tablaEnf.getValueAt(tablaEnf.getSelectedRow(), 0));
        contenido += "\n\nMÁXIMA:\n : " + String.valueOf(tablaEnf.getValueAt(tablaEnf.getSelectedRow(), 1));
        contenido += "\n\nMÍNIMA:\n : " + String.valueOf(tablaEnf.getValueAt(tablaEnf.getSelectedRow(), 2));
        contenido += "\n\nGLUCOSA:\n : " + String.valueOf(tablaEnf.getValueAt(tablaEnf.getSelectedRow(), 3));
         contenido += "\n\nPESO:\n : " + String.valueOf(tablaEnf.getValueAt(tablaEnf.getSelectedRow(), 4));
    
        JTextArea t = new JTextArea(20, 60);
        t.setText(contenido);
        t.setEditable(false);
        t.setLineWrap(false);
        t.setFocusable(false);
        t.setAutoscrolls(false);
        t.setMargin(new Insets(10, 10, 10, 10));
        
        JOptionPane.showMessageDialog(this,new JScrollPane(t), "INFORME", 1); 
}
}



}
