/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import utilidades.Encriptado;
import utilidades.UtilidadEmail;
import utilidades.Utilidades;

/**
 *
 * @author mario
 */
public class NuevoInformeMedico extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoInformeMedico.class.getName());

    public String dniPacienteRescatado = /*Encriptado.Mcano_Desencriptar(*/NuevaConsulta.pacienteConsultado.getDni()/*)*/; // Se desencripta ya 2 veces, lo hace el metodo de Conexion
    public static int numero_colegiadoo = Integer.parseInt(Login.datosPersonal[1]);
    
    
    /**
     * Creates new form NuevoInformeMedico
     */
    public NuevoInformeMedico(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

        campoDNI.setText(dniPacienteRescatado);
        campoDNI.setEnabled(true);
        campoDNI.setEditable(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabell = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabell1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTratamiento = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaObservaciones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(709, 532));
        setMinimumSize(new java.awt.Dimension(709, 532));
        setPreferredSize(new java.awt.Dimension(709, 619));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 204, 204));
        labelTitulo.setText("NUEVO INFORME MÉDICO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabell)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(833, Short.MAX_VALUE)
                    .addComponent(jLabell1)
                    .addGap(13, 13, 13)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabell1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(484, 484, 484)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setText("DNI PACIENTE");

        campoDNI.setName("DNI"); // NOI18N
        campoDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDNIFocusLost(evt);
            }
        });

        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("DIAGNÓSTICO");

        jLabel5.setText("TRATAMIENTO");

        jLabel6.setText("OBSERVACIONES");

        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        areaDiagnostico.setColumns(20);
        areaDiagnostico.setRows(5);
        areaDiagnostico.setName("DIANGÓSTICO"); // NOI18N
        areaDiagnostico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaDiagnosticoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaDiagnosticoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(areaDiagnostico);

        areaTratamiento.setColumns(20);
        areaTratamiento.setRows(5);
        areaTratamiento.setName("TRATAMIENTO"); // NOI18N
        areaTratamiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaTratamientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaTratamientoFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(areaTratamiento);

        areaObservaciones.setColumns(20);
        areaObservaciones.setRows(5);
        areaObservaciones.setAutoscrolls(false);
        areaObservaciones.setName("OBSERVACIONES"); // NOI18N
        areaObservaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaObservacionesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaObservacionesFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(areaObservaciones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCancelar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void campoDNIFocusGained(java.awt.event.FocusEvent evt) {                                     
        campoDNI.setBackground(Color.LIGHT_GRAY);
    }                                    

    private void campoDNIFocusLost(java.awt.event.FocusEvent evt) {                                   
        campoDNI.setBackground(Color.WHITE);
    }                                  

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        registroInformeMedico();
    }                                            

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        dispose();
    }                                             

    private void areaDiagnosticoFocusGained(java.awt.event.FocusEvent evt) {                                            
        areaDiagnostico.setBackground(Color.LIGHT_GRAY);
    }                                           

    private void areaDiagnosticoFocusLost(java.awt.event.FocusEvent evt) {                                          
        areaDiagnostico.setBackground(Color.WHITE);
    }                                         

    private void areaTratamientoFocusGained(java.awt.event.FocusEvent evt) {                                            
        areaTratamiento.setBackground(Color.LIGHT_GRAY);
    }                                           

    private void areaTratamientoFocusLost(java.awt.event.FocusEvent evt) {                                          
        areaTratamiento.setBackground(Color.WHITE);
    }                                         

    private void areaObservacionesFocusGained(java.awt.event.FocusEvent evt) {                                              
        areaObservaciones.setBackground(Color.LIGHT_GRAY);
    }                                             

    private void areaObservacionesFocusLost(java.awt.event.FocusEvent evt) {                                            
        areaObservaciones.setBackground(Color.WHITE);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NuevoInformeMedico dialog = new NuevoInformeMedico(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea areaDiagnostico;
    private javax.swing.JTextArea areaObservaciones;
    private javax.swing.JTextArea areaTratamiento;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabell;
    private javax.swing.JLabel jLabell1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration                   

    /* 
    registroInformeMedico();
    
    dispose();
    
    // poner blanco y gris

    */
    
    private modelo.Consulta informeMedicoNuevo;
    
    // JFileChooser selector = new JFileChooser(); // En este programa no adjuntamos archivos en email
    
    public void registroInformeMedico() {
        
        Conexion.conectar();
        
        try {
            
            if (!Utilidades.ValidaCampoVacio(campoDNI)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(areaDiagnostico)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(areaTratamiento)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(areaObservaciones)) {
                return;
            } else {
                
                JOptionPane.showMessageDialog(null, "Todos campos son correctos");
                
                String dnip = Encriptado.Mcano_Encriptar(dniPacienteRescatado);
                Date fech = new Date();
                String diag = areaDiagnostico.getText();
                String tra = areaTratamiento.getText();
                String obse = areaObservaciones.getText();
              
                
                informeMedicoNuevo = new modelo.Consulta(
                dnip,
                fech,
                diag,
                tra,
                obse,
                numero_colegiadoo
                );
                
                if (Conexion.registrarConsultaMedica(informeMedicoNuevo)) {
                    JOptionPane.showMessageDialog(null, "Registro de consulta médica correcto.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error en el registro. Inténtelo más tarde o póngase en contacto con el administrador del sistema.");
                }
                
                areaDiagnostico.setText("");
                areaTratamiento.setText("");
                areaObservaciones.setText("");
                
                Conexion.cerrarConexion();

            }
            
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + ex.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }
         
    }


}


