 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import utilidades.Encriptado;
import utilidades.UtilidadEmail;
import utilidades.Utilidades;

/**
 *
 * @author mario
 */
public class NuevaCitaEnfermeria extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevaCitaEnfermeria.class.getName());

    public String dniPacienteRescatado = /*Encriptado.Mcano_Desencriptar(*/NuevaConsulta.pacienteConsultado.getDni()/*)*/;  // Se desencripta ya 2 veces, lo hace el metodo de Conexion
    public String nombreCompletoPacienteRescatado = NuevaConsulta.pacienteConsultado.getNombre() + " " + NuevaConsulta.pacienteConsultado.getApellidos();
    public String emailPacienteRescatado = NuevaConsulta.pacienteConsultado.getEmail();
    
    
    /**
     * Creates new form NuevaCitaEnfermeria
     */
    public NuevaCitaEnfermeria(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

        campoDNI.setText(dniPacienteRescatado);
        campoDNI.setEditable(false);
        campoNombreYApellidos.setText(nombreCompletoPacienteRescatado);
        campoNombreYApellidos.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabell = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabell1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        campoNombreYApellidos = new javax.swing.JTextField();
        comboFecha = new javax.swing.JComboBox<>();
        botonRegistrar = new javax.swing.JButton();
        comboHora = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(709, 532));
        setMinimumSize(new java.awt.Dimension(709, 532));
        setPreferredSize(new java.awt.Dimension(709, 532));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 204, 204));
        labelTitulo.setText("NUEVA CITA ENFERMERÍA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabell)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(833, Short.MAX_VALUE)
                    .addComponent(jLabell1)
                    .addGap(13, 13, 13)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabell1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(484, 484, 484)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setText("DNI");

        jLabel4.setText("NOMBRE Y APELLIDOS");

        jLabel5.setText("FECHA");

        jLabel6.setText("HORA");

        campoDNI.setName("DNI"); // NOI18N
        campoDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDNIFocusLost(evt);
            }
        });

        campoNombreYApellidos.setName("NOMBRE Y APELLIDOS"); // NOI18N
        campoNombreYApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreYApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreYApellidosFocusLost(evt);
            }
        });

        comboFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Una semana", "Dos semanas", "Un mes" }));
        comboFecha.setName("FECHA"); // NOI18N
        comboFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboFechaFocusLost(evt);
            }
        });

        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        comboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "8", "8,30", "9", "9,30", "10", "10,30", "11", "11,30", "12", "12,30", "13", "13,30", "14" }));
        comboHora.setName("HORA"); // NOI18N
        comboHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboHoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboHoraFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(campoNombreYApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(campoDNI)
                    .addComponent(comboFecha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNombreYApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(comboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(botonRegistrar)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDNIFocusGained
        campoDNI.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_campoDNIFocusGained

    private void campoDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDNIFocusLost
        campoDNI.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoDNIFocusLost

    private void campoNombreYApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreYApellidosFocusGained
        campoNombreYApellidos.setBackground(Color.LIGHT_GRAY);
        campoNombreYApellidos.setText("");
    }//GEN-LAST:event_campoNombreYApellidosFocusGained

    private void campoNombreYApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreYApellidosFocusLost
        campoNombreYApellidos.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoNombreYApellidosFocusLost

    private void comboFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboFechaFocusGained
        comboFecha.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_comboFechaFocusGained

    private void comboFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboFechaFocusLost
        comboFecha.setBackground(Color.WHITE);
    }//GEN-LAST:event_comboFechaFocusLost

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        registroCitaEnfermeria();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void comboHoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboHoraFocusGained
        comboHora.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_comboHoraFocusGained

    private void comboHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboHoraFocusLost
        comboHora.setBackground(Color.WHITE);
    }//GEN-LAST:event_comboHoraFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NuevaCitaEnfermeria dialog = new NuevaCitaEnfermeria(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoNombreYApellidos;
    private javax.swing.JComboBox<String> comboFecha;
    private javax.swing.JComboBox<String> comboHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabell;
    private javax.swing.JLabel jLabell1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
    
    /* 
    registroCitaEnfermeria();
    
    
    // poner blanco y gris

    */
    
    private modelo.Cita citaEnfermeriaNueva;
    
    // JFileChooser selector = new JFileChooser(); // En este programa no adjuntamos archivos en email
    
    public void registroCitaEnfermeria() {
        
        Conexion.conectar();
        
        try {
            
            if (!Utilidades.ValidaCampoVacio(campoDNI)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(campoNombreYApellidos)) {
                return;
            } else if (!Utilidades.ValidaComboVacio(comboFecha)) {
                return;
            } else if (!Utilidades.ValidaComboVacio(comboHora)) {
                return;
            } else {
                
                JOptionPane.showMessageDialog(null, "Todos campos son correctos");
                
                String dnip = Encriptado.Mcano_Encriptar(dniPacienteRescatado);
                String nom = Encriptado.Mcano_Encriptar(nombreCompletoPacienteRescatado);
                
                Calendar hoy = Calendar.getInstance();  // Calendar opera con dias, si fuera c....
                Date fech = hoy.getTime();              // variable que sí será Date
                
                if (comboFecha.getSelectedItem().toString().equals("Una semana")) {
                    
                    hoy.add(Calendar.DAY_OF_MONTH, 7);
                    fech = hoy.getTime();
                    
                } else if (comboFecha.getSelectedItem().toString().equals("Dos semanas")) {
                    
                    hoy.add(Calendar.DAY_OF_MONTH, 14);
                    fech = hoy.getTime();
                    
                } else if (comboFecha.getSelectedItem().toString().equals("Un mes")) {
                    
                    hoy.add(Calendar.DAY_OF_MONTH, 30);
                    fech = hoy.getTime();
                }
                
                Double hor = Double.parseDouble(comboFecha.getSelectedItem().toString());
                
                citaEnfermeriaNueva = new modelo.Cita(
                dnip,
                nom,
                fech,
                hor
                );
                
                if (Conexion.registrarCitaEnfermeria(citaEnfermeriaNueva)) {
                    JOptionPane.showMessageDialog(null, "Registro de cita de enfermería correcto.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error en el registro.");
                }
                
                SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                String diaFormateado = formato.format(fech);
                
                
                // EMAIL
                
                String msg = "------------ Datos de la cita ----------- " +
                "\nDNI del paciente: " + dniPacienteRescatado +
                "\nNombre: " + nombreCompletoPacienteRescatado +
                "\nDía: " + diaFormateado +
                "\nHora: " + hor +        
                "\n--------------------------------------------: " +        
                "<p><img src=\"https://reynaldo.com//firmacorreo/firmacorreo.png\"></p>" +        
                "\nHas recibido este email porque has solicitado una cita en el centro médico. " +   
                "\nPor favor, no responda a este correo electrónico: ha sido generado automáticamente.";     
                        
                // sin otro if fuera porque no adjuntamos ningun archivo y solo usamos el metodo con html 
                
                UtilidadEmail ue = new UtilidadEmail("Citación médica a " + nombreCompletoPacienteRescatado, msg, emailPacienteRescatado);
                
                if (ue.enaviaMailHtml()) {
                    JOptionPane.showMessageDialog(this, "Correo electrónico enviado correctamente", "Envío de correo electrónico.", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Ha habido un error en el envío de correo electrónico", "Envío de correo electrónico.", JOptionPane.ERROR_MESSAGE);
                }
                 
                comboFecha.setSelectedIndex(0);
                comboFecha.setSelectedIndex(0);
                
                Conexion.cerrarConexion();
                dispose(); 
            }
            
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + ex.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }
         
    }
    
}
    
     
