/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import utilidades.Encriptado;
import utilidades.Utilidades;
import static vistas.NuevoInformeEnfermeria.numero_colegiadoo;

/**
 *
 * @author mario
 */
public class NuevoPaciente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoPaciente.class.getName());

    // public String dniPacienteRescatado = Encriptado.Mcano_Desencriptar(NuevaConsulta.pacienteConsultado.getDni()); // era de un paciente existente, no nuevo
    // public static String dnipaciente; solo declarado, por si no se asigna bien la variable rescatada
    public static String dnipaciente = NuevaConsulta.dniPacienteNuevo; // podria dar error antes no era static
    
    /**
     * Creates new form NuevoPaciente
     */
    public NuevoPaciente(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // dnipaciente = NuevaConsulta.dniPacienteNuevo; // ASIGNAR AQUI LA VARIABLE RESCATADA
        campoDNI.setText(dnipaciente);
        campoDNI.setEnabled(true);
        campoDNI.setEditable(false);
        
        // Falta un if que comprueba que si no se rescata, podamos escribirlo a mano
        
        Conexion.conectar();
        Conexion.cargasComboCp(comboCP);
        Conexion.cerrarConexion();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupTabaquismo = new javax.swing.ButtonGroup();
        buttonGroupAlcohol = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        panelUno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoDNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        fechaUno = new com.toedter.calendar.JDateChooser();
        campoTelefono = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        comboCP = new javax.swing.JComboBox<>();
        botonMujer = new javax.swing.JRadioButton();
        botonHombre = new javax.swing.JRadioButton();
        botonNO = new javax.swing.JRadioButton();
        botonOtros = new javax.swing.JRadioButton();
        botonSI = new javax.swing.JRadioButton();
        botonOCASIONAL = new javax.swing.JRadioButton();
        botonHABITUAL = new javax.swing.JRadioButton();
        botonNULO = new javax.swing.JRadioButton();
        panelDos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaUno = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDos = new javax.swing.JTextArea();
        botonRegistrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabell = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabell1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(986, 596));
        setMinimumSize(new java.awt.Dimension(986, 596));
        setPreferredSize(new java.awt.Dimension(986, 596));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        panelUno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelUno.setOpaque(false);

        jLabel3.setText("DNI ");

        campoDNI.setName("DNI"); // NOI18N
        campoDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDNIFocusLost(evt);
            }
        });

        jLabel4.setText("NOMBRE");

        jLabel5.setText("APELLIDOS");

        jLabel6.setText("FECHA NACIMIENTO");

        jLabel7.setText("TELÉFONO");

        jLabel8.setText("EMAIL");

        jLabel9.setText("CÓDIGO POSTAL");

        jLabel10.setText("SEXO");

        jLabel11.setText("TABAQUISMO");

        jLabel12.setText("CONSUMO ALCOHOL");

        campoNombre.setName("NOMBRE"); // NOI18N
        campoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreFocusLost(evt);
            }
        });

        campoApellidos.setName("APELLIDOS"); // NOI18N
        campoApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoApellidosFocusLost(evt);
            }
        });

        fechaUno.setName("FECHA NACIMIENTO"); // NOI18N
        fechaUno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaUnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fechaUnoFocusLost(evt);
            }
        });

        campoTelefono.setName("TELÉFONO"); // NOI18N
        campoTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefonoFocusLost(evt);
            }
        });

        campoEmail.setName("EMAIL"); // NOI18N
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });

        comboCP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboCP.setName("CÓDIGO POSTAL"); // NOI18N
        comboCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboCPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboCPFocusLost(evt);
            }
        });

        buttonGroupSexo.add(botonMujer);
        botonMujer.setText("Mujer");
        botonMujer.setName("MUJER"); // NOI18N

        buttonGroupSexo.add(botonHombre);
        botonHombre.setText("Hombre");
        botonHombre.setName("HOMBRE"); // NOI18N

        buttonGroupTabaquismo.add(botonNO);
        botonNO.setText("No");
        botonNO.setName("NO"); // NOI18N

        buttonGroupSexo.add(botonOtros);
        botonOtros.setText("Otros");
        botonOtros.setName("OTROS"); // NOI18N

        buttonGroupTabaquismo.add(botonSI);
        botonSI.setText("Si");
        botonSI.setName("SI"); // NOI18N

        buttonGroupAlcohol.add(botonOCASIONAL);
        botonOCASIONAL.setText("Ocasional");
        botonOCASIONAL.setName("OCASIONAL"); // NOI18N

        buttonGroupAlcohol.add(botonHABITUAL);
        botonHABITUAL.setText("Habitual");
        botonHABITUAL.setName("HABITUAL"); // NOI18N

        buttonGroupAlcohol.add(botonNULO);
        botonNULO.setText("Nulo");
        botonNULO.setName("NULO"); // NOI18N

        javax.swing.GroupLayout panelUnoLayout = new javax.swing.GroupLayout(panelUno);
        panelUno.setLayout(panelUnoLayout);
        panelUnoLayout.setHorizontalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUnoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUnoLayout.createSequentialGroup()
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(fechaUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelUnoLayout.createSequentialGroup()
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(comboCP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelUnoLayout.createSequentialGroup()
                                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonMujer)
                                    .addComponent(botonNO)
                                    .addComponent(botonOCASIONAL))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonSI)
                                    .addGroup(panelUnoLayout.createSequentialGroup()
                                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonHombre)
                                            .addComponent(botonHABITUAL))
                                        .addGap(26, 26, 26)
                                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonNULO)
                                            .addComponent(botonOtros))))
                                .addGap(3, 3, 3)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelUnoLayout.setVerticalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                                                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                                                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                                                                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel3)
                                                                    .addComponent(campoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel4))
                                                            .addComponent(campoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel5))
                                                    .addComponent(campoApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6))
                                            .addComponent(fechaUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(campoEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(comboCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(botonMujer)
                    .addComponent(botonHombre)
                    .addComponent(botonOtros))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(botonNO)
                    .addComponent(botonSI))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(botonOCASIONAL)
                    .addComponent(botonHABITUAL)
                    .addComponent(botonNULO))
                .addGap(14, 14, 14))
        );

        panelDos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SALUD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDos.setOpaque(false);

        jLabel13.setText("Antecedentes familiares destacables");

        jLabel14.setText("Personal (alergias, cirugías, enfermedades...)");

        areaUno.setColumns(20);
        areaUno.setRows(5);
        areaUno.setName("ANTECEDENTES"); // NOI18N
        areaUno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaUnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaUnoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(areaUno);

        areaDos.setColumns(20);
        areaDos.setRows(5);
        areaDos.setName("PERSONAL"); // NOI18N
        areaDos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaDosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaDosFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(areaDos);

        javax.swing.GroupLayout panelDosLayout = new javax.swing.GroupLayout(panelDos);
        panelDos.setLayout(panelDosLayout);
        panelDosLayout.setHorizontalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDosLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelDosLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(219, 219, 219))
                    .addGroup(panelDosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelDosLayout.setVerticalGroup(
            panelDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDos, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegistrar)
                .addGap(207, 207, 207))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRegistrar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 204, 204));
        labelTitulo.setText("NUEVO PACIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabell)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(833, Short.MAX_VALUE)
                    .addComponent(jLabell1)
                    .addGap(13, 13, 13)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabell1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(484, 484, 484)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDNIFocusGained
        campoDNI.setBackground(Color.LIGHT_GRAY);
        campoDNI.setText("");
    }//GEN-LAST:event_campoDNIFocusGained

    private void campoDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDNIFocusLost
        campoDNI.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoDNIFocusLost

    private void campoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusGained
        campoNombre.setBackground(Color.LIGHT_GRAY);
        campoNombre.setText("");
    }//GEN-LAST:event_campoNombreFocusGained

    private void campoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusLost
        campoNombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoNombreFocusLost

    private void campoApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoApellidosFocusGained
        campoApellidos.setBackground(Color.LIGHT_GRAY);
        campoApellidos.setText("");
    }//GEN-LAST:event_campoApellidosFocusGained

    private void campoApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoApellidosFocusLost
        campoApellidos.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoApellidosFocusLost

    private void campoTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonoFocusGained
        campoTelefono.setBackground(Color.LIGHT_GRAY);
        campoTelefono.setText("");
    }//GEN-LAST:event_campoTelefonoFocusGained

    private void campoTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonoFocusLost
        campoTelefono.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoTelefonoFocusLost

    private void campoEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusGained
        campoEmail.setBackground(Color.LIGHT_GRAY);
        campoEmail.setText("");
    }//GEN-LAST:event_campoEmailFocusGained

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
        campoEmail.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoEmailFocusLost

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        registroPaciente();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void fechaUnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaUnoFocusGained
        fechaUno.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_fechaUnoFocusGained

    private void fechaUnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaUnoFocusLost
        fechaUno.setBackground(Color.WHITE);
    }//GEN-LAST:event_fechaUnoFocusLost

    private void comboCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboCPFocusGained
        comboCP.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_comboCPFocusGained

    private void comboCPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboCPFocusLost
        comboCP.setBackground(Color.WHITE);
    }//GEN-LAST:event_comboCPFocusLost

    private void areaUnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaUnoFocusGained
        areaUno.setBackground(Color.LIGHT_GRAY);
        areaUno.setText("");
    }//GEN-LAST:event_areaUnoFocusGained

    private void areaUnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaUnoFocusLost
        areaUno.setBackground(Color.WHITE);
    }//GEN-LAST:event_areaUnoFocusLost

    private void areaDosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaDosFocusGained
        areaDos.setBackground(Color.LIGHT_GRAY);
        areaDos.setText("");
    }//GEN-LAST:event_areaDosFocusGained

    private void areaDosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaDosFocusLost
        areaDos.setBackground(Color.WHITE);
    }//GEN-LAST:event_areaDosFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NuevoPaciente dialog = new NuevoPaciente(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDos;
    private javax.swing.JTextArea areaUno;
    private javax.swing.JRadioButton botonHABITUAL;
    private javax.swing.JRadioButton botonHombre;
    private javax.swing.JRadioButton botonMujer;
    private javax.swing.JRadioButton botonNO;
    private javax.swing.JRadioButton botonNULO;
    private javax.swing.JRadioButton botonOCASIONAL;
    private javax.swing.JRadioButton botonOtros;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JRadioButton botonSI;
    private javax.swing.ButtonGroup buttonGroupAlcohol;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.ButtonGroup buttonGroupTabaquismo;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoDNI;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox<String> comboCP;
    private com.toedter.calendar.JDateChooser fechaUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabell;
    private javax.swing.JLabel jLabell1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelDos;
    private javax.swing.JPanel panelUno;
    // End of variables declaration//GEN-END:variables
    
    /*
    
    registroPaciente();
    
    blanco y gris
    
    */

    private modelo.Paciente pacienteNuevo;
    
    public void registroPaciente() {
        
        Conexion.conectar();
        
         try {
            
            if (!Utilidades.ValidaFormuario(panelUno)) {
                return;
            } else if (!Utilidades.CompruebaFechaNacimiento(fechaUno)) {
                return;
            } else if (!Utilidades.CompruebaEntero(campoTelefono)) {
                Utilidades.AlertaValoresNumericos(campoTelefono);
            } else if (!Utilidades.ValidarTelefono(campoTelefono.getText())) {
                campoTelefono.setText("000000000");
                campoTelefono.setBackground(Color.RED);
            } else if (!Utilidades.ValidarEmail(campoEmail.getText())) {
                campoEmail.setText("xxx@xxx.xxx");
                campoEmail.setBackground(Color.RED);
            } else if (!Utilidades.ValidarCP(comboCP.getSelectedItem().toString())) {
                return;
            } else if (!Utilidades.ValidaBotonSexo(botonMujer, botonHombre, botonOtros)) {
                return;
            } else if (!Utilidades.ValidaBotonTabaquismo(botonNO, botonSI)) {
                return;
            } else if (!Utilidades.ValidaBotonAlcohol(botonOCASIONAL, botonHABITUAL, botonNULO)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(areaUno)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(areaDos)) {
                return;
            } else {
                
                JOptionPane.showMessageDialog(null, "Todos campos son correctos");
                
                String dnii = Encriptado.Mcano_Encriptar(campoDNI.getText());
                String nom = Encriptado.Mcano_Encriptar(campoNombre.getText());
                String ape = Encriptado.Mcano_Encriptar(campoApellidos.getText());
                Date fechnac = fechaUno.getDate();
                int tlf = Integer.parseInt(campoTelefono.getText());
                String ema = campoEmail.getText();
                int cpp = Integer.parseInt(comboCP.getSelectedItem().toString());
              
                String sex = null;
                
                if (botonMujer.isSelected()) {
                    sex = "M"; // el enum de la BBDD
                    botonHombre.setSelected(false);
                    botonOtros.setSelected(false);
                    
                } else if (botonHombre.isSelected()) {
                    sex = "H"; // el enum de la BBDD
                    botonMujer.setSelected(false);
                    botonOtros.setSelected(false);
                } else if (botonOtros.isSelected()) {
                    sex = "OTROS"; // el enum de la BBDD
                    botonHombre.setSelected(false);
                    botonMujer.setSelected(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Debes seleccionar un género.");
                    return; // o false segun el contexto
                }
                
                String taba = null;
                
                if (botonNO.isSelected()) {
                    taba = "NO"; // el enum de la BBDD
                    botonSI.setSelected(false);
                    
                } else if (botonSI.isSelected()) {
                    taba = "SI"; 
                    botonNO.setSelected(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Debes seleccionar una opción respecto al consumo de tabaco.");
                    return;
                }
                
                
                String consu = null;
                
                if (botonOCASIONAL.isSelected()) {
                    consu = "Ocasional"; // el enum de la BBDD
                    botonHABITUAL.setSelected(false);
                    botonNULO.setSelected(false);
                    
                } else if (botonHABITUAL.isSelected()) {
                    consu = "Habitual"; // el enum de la BBDD
                    botonOCASIONAL.setSelected(false);
                    botonNULO.setSelected(false);
                } else if (botonNULO.isSelected()) {
                    consu = "Nulo"; // el enum de la BBDD
                    botonOCASIONAL.setSelected(false);
                    botonHABITUAL.setSelected(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Debes seleccionar una opción respecto al consumo de alcohol.");
                    return; // o false segun el contexto
                }
                
                String antec = areaUno.getText();
                String dat = areaDos.getText();
                Date fechreg = new Date();
                
                pacienteNuevo = new modelo.Paciente(
                dnii,
                nom,
                ape,
                fechnac,
                tlf,
                ema,
                cpp,
                sex,
                taba,
                consu,
                antec,
                dat,
                fechreg
                );
                
                if (Conexion.registrarPaciente(pacienteNuevo)) {
                    JOptionPane.showMessageDialog(null, "Registro del paciente correcto.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error en el registro. Inténtelo más tarde o póngase en contacto con el administrador del sistema.");
                }
                
                Utilidades.LimpiarFormulario(panelUno);
                Utilidades.ResetarFecha(fechaUno);
                
                buttonGroupSexo.clearSelection();
                buttonGroupTabaquismo.clearSelection();
                buttonGroupAlcohol.clearSelection();
                
                Utilidades.LimpiarFormulario(panelDos);

                Conexion.cerrarConexion();

            }
            
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + ex.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }
         
    }


}


