/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import bbdd.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;
import utilidades.Encriptado;
import utilidades.Utilidades;

/**
 *
 * @author mario
 */
public class PersonalMedico extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PersonalMedico.class.getName());

    
    
    /**
     * Creates new form PersonalMedico
     */
    public PersonalMedico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelUno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoCole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        campoUsuario = new javax.swing.JTextField();
        campoPass = new javax.swing.JPasswordField();
        comboTipo = new javax.swing.JComboBox<>();
        botonRegistrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabell = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabell1 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        panelUno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelUno.setOpaque(false);

        jLabel3.setText("Nº COLEGIADO");

        campoCole.setName("Nº DE COLEGIADO"); // NOI18N
        campoCole.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoColeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoColeFocusLost(evt);
            }
        });

        jLabel4.setText("NOMBRE");

        jLabel5.setText("APELLIDOS");

        jLabel6.setText("TELÉFONO");

        jLabel7.setText("USUARIO");

        jLabel8.setText("CONTRASEÑA");

        jLabel9.setText("TIPO");

        campoNombre.setName("NOMBRE"); // NOI18N
        campoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreFocusLost(evt);
            }
        });

        campoApellidos.setName("APELLIDOS"); // NOI18N
        campoApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoApellidosFocusLost(evt);
            }
        });

        campoTelefono.setName("TELÉFONO"); // NOI18N
        campoTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefonoFocusLost(evt);
            }
        });

        campoUsuario.setName("USUARIO"); // NOI18N
        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusLost(evt);
            }
        });

        campoPass.setName("CONTRASEÑA"); // NOI18N
        campoPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPassFocusLost(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "MEDICO", "ENFERMERIA", "ADMIN" }));
        comboTipo.setName("TIPO DE USUARIO"); // NOI18N
        comboTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboTipoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboTipoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelUnoLayout = new javax.swing.GroupLayout(panelUno);
        panelUno.setLayout(panelUnoLayout);
        panelUnoLayout.setHorizontalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUnoLayout.createSequentialGroup()
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCole, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelUnoLayout.createSequentialGroup()
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelUnoLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(45, 45, 45))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUnoLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(panelUnoLayout.createSequentialGroup()
                                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)))
                        .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoUsuario)
                            .addComponent(campoTelefono)
                            .addComponent(campoPass)
                            .addComponent(comboTipo, 0, 244, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );
        panelUnoLayout.setVerticalGroup(
            panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        botonRegistrar.setText("REGISTRAR");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(botonRegistrar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(botonRegistrar)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabell1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 204, 204));
        labelTitulo.setText("PERSONAL MÉDICO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabell)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(833, Short.MAX_VALUE)
                    .addComponent(jLabell1)
                    .addGap(13, 13, 13)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabell1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(484, 484, 484)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        registroPersonal();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void campoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusLost
        campoUsuario.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoUsuarioFocusLost

    private void campoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusGained
        campoUsuario.setBackground(Color.LIGHT_GRAY);
        campoUsuario.setText("");
    }//GEN-LAST:event_campoUsuarioFocusGained

    private void campoTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonoFocusLost
        campoTelefono.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoTelefonoFocusLost

    private void campoTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonoFocusGained
        campoTelefono.setBackground(Color.LIGHT_GRAY);
        campoTelefono.setText("");
    }//GEN-LAST:event_campoTelefonoFocusGained

    private void campoApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoApellidosFocusLost
        campoApellidos.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoApellidosFocusLost

    private void campoApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoApellidosFocusGained
        campoApellidos.setBackground(Color.LIGHT_GRAY);
        campoApellidos.setText("");
    }//GEN-LAST:event_campoApellidosFocusGained

    private void campoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusLost
        campoNombre.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoNombreFocusLost

    private void campoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusGained
        campoNombre.setBackground(Color.LIGHT_GRAY);
        campoNombre.setText("");
    }//GEN-LAST:event_campoNombreFocusGained

    private void campoColeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoColeFocusLost
        campoCole.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoColeFocusLost

    private void campoColeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoColeFocusGained
        campoCole.setBackground(Color.LIGHT_GRAY);
        campoCole.setText("");
    }//GEN-LAST:event_campoColeFocusGained

    private void campoPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPassFocusGained
        campoPass.setBackground(Color.LIGHT_GRAY);
        campoPass.setText("");
    }//GEN-LAST:event_campoPassFocusGained

    private void campoPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPassFocusLost
        campoPass.setBackground(Color.WHITE);
    }//GEN-LAST:event_campoPassFocusLost

    private void comboTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTipoFocusGained
        comboTipo.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_comboTipoFocusGained

    private void comboTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTipoFocusLost
        comboTipo.setBackground(Color.WHITE);
    }//GEN-LAST:event_comboTipoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PersonalMedico dialog = new PersonalMedico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoCole;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPasswordField campoPass;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabell;
    private javax.swing.JLabel jLabell1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelUno;
    // End of variables declaration//GEN-END:variables

    /*
    
    registroPersonal();
    
    
    blanco gris
    
    campoTelefono.setText("");
    
    
    
    */
    
    private modelo.Personal personalNuevo;
    
    public void registroPersonal() {
        
        Conexion.conectar();    
        
         try {
            
            if (!Utilidades.ValidaCampoVacio(campoCole)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(campoNombre)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(campoApellidos)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(campoTelefono)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(campoUsuario)) {
                return;
            } else if (!Utilidades.ValidaCampoVacio(campoPass)) {
                return;
            } else if (!Utilidades.ValidaComboVacio(comboTipo)) {
                return;
            } else if (!Utilidades.CompruebaEntero(campoCole)) {
                Utilidades.AlertaValoresNumericos(campoCole);
                return;
            } else if (!Utilidades.ValidarColegiado(campoCole.getText())) {
                campoCole.setBackground(Color.red);
                return;
            } else if (!Utilidades.CompruebaEntero(campoTelefono)) {
                Utilidades.AlertaValoresNumericos(campoTelefono);
                return;
            } else if (!Utilidades.ValidarTelefono(campoTelefono.getText())) {
                campoTelefono.setText("000000000");
                campoTelefono.setBackground(Color.RED);
                return;
            } else if (Conexion.compruebaNumeroColegiado(Integer.parseInt(campoCole.getText()))) {
                campoCole.setText("");
                campoCole.setBackground(Color.RED);
                JOptionPane.showMessageDialog(null, "Este nº de colegiado ya existe");
                return;
            } else if (Conexion.compruebaUser(campoUsuario.getText())) {
                campoUsuario.setText("");
                campoUsuario.setBackground(Color.RED);
                JOptionPane.showMessageDialog(null, "Este usuario ya existe");
                return;
            } else {
                
                JOptionPane.showMessageDialog(null, "Todos campos son correctos");
                
                int numc = Integer.parseInt(campoCole.getText());
                String nom = campoNombre.getText();
                String ape = campoApellidos.getText();
                int tel = Integer.parseInt(campoTelefono.getText());
                String usu = campoUsuario.getText();
                
                char[] passArray = campoPass.getPassword(); 
                String pass = new String(passArray);
                String passEncriptada = Encriptado.Mcano_Encriptar(pass);
                
                String tip = comboTipo.getSelectedItem().toString();
                
 
                personalNuevo = new modelo.Personal(
                numc,
                nom,
                ape,
                tel,
                usu,
                passEncriptada,
                tip
                );
                
                if (Conexion.registrarPersonal(personalNuevo)) {
                    JOptionPane.showMessageDialog(null, "Registro del personal correcto.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error en el registro. Inténtelo más tarde o póngase en contacto con el administrador del sistema.");
                }
                
                campoCole.setText("");
                campoNombre.setText("");
                campoApellidos.setText("");
                campoTelefono.setText("");
                campoUsuario.setText("");
                campoPass.setText("");
                comboTipo.setSelectedIndex(0);

                Conexion.cerrarConexion();

            }
            
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + ex.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }
         
    }


}


